services:
  metabase:
    image: metabase/metabase:latest
    depends_on:
      - postgres
      - postgres-ext-db
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabasepassw
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: metabasepassw
    volumes:
      - metabasepostgresdbdata:/var/lib/postgresql/data
    networks:
      - metanet1
  postgres-ext-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=externaldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5440:5432
    volumes:
      - postgresdbdata:/var/lib/postgresql/data
    restart: always
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge

volumes:
  metabasepostgresdbdata:
  postgresdbdata:
